import NextTopLoader from 'nextjs-toploader';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from '../components/Navbar';
import { Toaster } from 'react-hot-toast';
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"

      >
        <Providers>
          <Navbar />

          <NextTopLoader
            color="#facc15"
            showSpinner={false}
            height={3}
            speed={400}
            shadow="0 0 10px #facc15, 0 0 5px #facc15"
          />


          {children}
          <Toaster position='bottom-right' />
        </Providers>
      </body>
    </html>
  );
}
